config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  devise_for :users
  get 'users/:id', to: 'users#show', as: 'user'

  resources :books, only: [:new, :create, :show, :index]
  get 'books/:id/processing', to: 'books#processing', as: 'processing'

  resources :contacts, only: [:show]
  get 'invalid_contacts', to: 'contacts#invalid_contact'
  get 'valid_contacts', to: 'contacts#valid_contact' 
  get 'all_contacts', to: 'contacts#all_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :contacts
  has_one_attached :file
  enum status: { espera: 0, procesado: 1, fallido: 2, terminado: 3}
  
  validates :file, presence: true
  validate :csv_format

  def csv_format
    unless file.content_type.in?(['text/csv'])
      errors.add(:file, 'Must be a CSV file')
    end
  end

  def add_filename
    self.filename = (self.file.filename).to_s.downcase
    self.save
  end

  $contact = { errors: []}

  def processing_file(params)
    fields = ['name', 'date', 'phone', 'address', 'franchise', 'email']
    valid_contact = 0

    file = ActiveStorage::Blob.service.path_for(self.file.key)
    CSV.foreach(file, headers: true) do |row|
      $contact = { errors: [], name: '', date: '', phone: '', address: '', credit_card: '', franchise: '', email: '', user_id: self[:user_id] }
      if row.size != 6
        add_format_error('size')
        create_contact($contact)
        break
      end

      fields.each do |field|
          send("valid_#{field}", row[params["#{field}".to_sym].to_i])
      end

      valid_contact += 1 if $contact[:errors].size == 0
      create_contact($contact)
    end
    valid_contact > 0 ? self.terminado! : self.fallido!
  end

  def valid_name(name)
    $contact[:name] = name
    if name.present? 
      add_format_error('name') if name.match(/[!$%^&*()_+|~=`{}\[\]:";'<>?,.Ç¨\|@#¢∞¬÷“”≠´\\]/)
    else
      add_blank_error('name')
    end
  end

  def valid_date(date)
    $contact[:date] = date
    if date.present?
      begin
        Date.iso8601(date)
      rescue
        add_format_error('date')
      end
    else
      add_blank_error('date')
    end
  end

  def valid_phone(phone)
    $contact[:phone] = phone
    if phone.present?
      regex1 = /^[\(]\+[\d]{2}[\)][ ][\d]{3}[ ][\d]{3}[ ][\d]{2}[ ][\d]{2}$/
      regex2 = /^[\(]\+[\d]{2}[\)][ ][\d]{3}[-][\d]{3}[-][\d]{2}[-][\d]{2}$/
      add_format_error('phone') unless phone.match(regex1) || phone.match(regex2)
    else
      add_blank_error('phone')
    end
  end

  def valid_address(address)
    $contact[:address] = address
    add_blank_error('address') unless address.present?    
  end

  def valid_credit_card(franchise, credit_card_number)
    case franchise
      when 'mastercard', 'visa', 'discover', 'jcb'
        add_format_error('length') if credit_card_number.size != 16
      when 'american express'
        add_format_error('length') if credit_card_number.size != 15
      when 'dinner club'
        add_format_error('length') if credit_card_number.size != 14
    end
  end

  def valid_franchise(credit_card_number)
    if credit_card_number.present?
      $contact[:card_digit] = credit_card_number[credit_card_number.size-4..credit_card_number.size]

      $contact[:franchise] = case credit_card_number
        when /^5[1-5][0-9]{5,}|222[1-9][0-9]{3,}|22[3-9][0-9]{4,}|2[3-6][0-9]{5,}|27[01][0-9]{4,}|2720[0-9]{3,}$/#mastercard - 16
          'mastercard'
        when /^4[0-9]{6,}$/#visa - 16
          'visa'
        when /^3[47][0-9]{5,}$/#americanexpress - 15
          'american express'
        when /^3(?:0[0-5]|[68][0-9])[0-9]{4,}$/#dinnersclub - 14
          'dinner club'
        when /^6(?:011|5[0-9]{2})[0-9]{3,}$/#discover - 16
          'discover'
        when /^(?:2131|1800|35[0-9]{3})[0-9]{3,}$/#jcb - 16
          'jcb'
        else
          'unknow'
      end

      $contact[:franchise] != 'unknow' ? valid_credit_card($contact[:franchise], credit_card_number) : add_format_error('franchise')
    else
      add_blank_error('franchise')
    end

    $contact[:credit_card] = BCrypt::Password.create(credit_card_number)

  end

  def valid_email(email)
    $contact[:email] = email
    if email.present?
      regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      if email.match(regex)
        current_user = User.find(self[:user_id])
        add_format_error('email_exists') if current_user.contacts.where(email: email, is_ok: true).exists?
      else
        add_format_error('email')
      end
    else
      add_blank_error('email')
    end
  end

  def add_blank_error(field)
    $contact[:errors] << "field #{field} is blank"
  end

  def add_format_error(field)
    case field
      when 'franchise'
        $contact[:errors] << "unknow franchise"
      when 'length'
        $contact[:errors] << "invalid length of credit card number"
      when 'email_exist'
        $contact[:errors] << "another valid contact has this email"
      when 'size'
        $contact[:errors] << "this contact does not have the correct number of fields"
      else
        $contact[:errors] << "bad format in #{field} field"
    end
  end

  def create_contact(params)
    params[:is_ok] = params[:errors].size == 0 ? true : false
    contact = self.contacts.create(params.except(:errors))
    
    unless params[:is_ok]
      params[:errors].each do |error|
        contact.messages.create(description: error)
      end
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :contacts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  validates :email, :password, :username, presence: true
  validates :email, :username, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new()
  end

  def index
    @books = current_user.books
  end

  def create
    @book = Book.new(book_params) 
    if @book.save
      @book.add_filename
      redirect_to @book
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def processing
    @book = Book.find(params[:id])
    @book.processing_file(params)
  end

  private
  def book_params
    params.require(:book).permit(:file).merge(user: current_user)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
    @contact = Contact.find(params[:id])
  end

  def all_contact
    @contacts = current_user.contacts
  end

  def valid_contact
    @contacts = current_user.contacts.where(is_ok: true)
  end

  def invalid_contact
    @contacts = current_user.contacts.where(is_ok: false)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @valid_contacts = @user.contacts.where(is_ok: true)
    @invalid_contacts = @user.contacts.where(is_ok: false)
    @last_contacts = @user.contacts.last(5)
    @books = @user.books
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_table.html.erb
<table class='table'>
  <tr class="table-secondary">
    <th>Filename</th>
    <th>Status</th>
    <th>Create at</th>
    <th>options</th>
  </tr>
  <% obj.each do |book| %>
    <tr>
      <td><%= link_to book.filename, book_path(book) %></td>
      <td>
        <% if book.status == 'terminado' %> 
          <span class="badge badge-success"><%= book.status %></span>
        <% elsif book.status == 'espera' %>
          <span class="badge badge-warning"><%= book.status %></span>          
        <% else %>
          <span class="badge badge-danger"><%= book.status %></span>
        <% end %>
      </td>
      <td><%= book.created_at %></td>
      <td><%= link_to 'view', book_path(book), class: 'btn btn-primary' %></td>
    </tr>
  <% end %>
</table>

app/views/books/index.html.erb
<h1>My Books</h1><br><br>

<%= link_to 'Import new book', new_book_path, class: 'btn btn-success mb-3' %>

<%= render 'book_table', obj: @books %>

app/views/books/new.html.erb
<h1>New book</h1><br><br>

<p class="lead">Recomendations to avoid future processing errors</p>
<p>* Your file must have csv format</p>
<p>* Your file should have 6 columns</p>
<p>* Your file should have the next columns (name, date, phone, address, franchise, email) </p>
<br>
<%= form_with model: @book do |f| %>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <%= f.label :file %>
  <%= f.file_field :file %><br>
  <br>
  <%= f.submit 'Import Book', class: 'btn btn-success' %>
<% end %>

app/views/books/show.html.erb
<h1><%= (@book.file.filename).to_s.downcase %></h1>
<table>
  <tr>
    <td class="lead pr-5">Created by:</td>
    <td class="lead">Status:</td>
  </tr>
  <tr>
    <td>
      <p class="lead">
        <%= @book.user.username %></td>
      </p>
    <td>
      <p class="lead">
        <% if @book.status == 'terminado' %> 
          <span class="badge badge-success"><%= @book.status %></span>
        <% else %>
          <span class="badge badge-warning"><%= @book.status %></span>
        <% end %>
      </p>
    </td>
  </tr>
</table><br><br>





<% if @book.status == 'espera' %>

  <p class="lead">Recomendations</p>
  <p>* Organize the columns of your file, assigned the numbers from 0 to 5</p>
  <p>* be careful when assigning the numbers in the fields to avoid errors when processing the contacts </p>

  <%= form_with url: processing_path(@book), method: 'GET' do |f| %>
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :date %>
          <%= f.text_field :date, class: 'form-control' %>
        </div>
      </div>

      <div class="col">
        <div class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :address %>
          <%= f.text_field :address, class: 'form-control' %>
        </div>
      </div>

      <div class="col">
        <div class="form-group">
          <%= f.label :franchise %>
          <%= f.text_field :franchise, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div>
      </div>
    </div>
    
  </div>
    <%= f.submit 'Processing', class: 'btn btn-success mb-5' %>
  <% end %>
<% end %>

<%= render 'contacts/contact_table', obj: @book.contacts %>

app/views/contacts/_contact_table.html.erb
<table class='table'>
  <tr class="table-secondary">
    <th>Name</th>
    <th>Date</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Franchise</th>
    <th>Card Digits</th>
    <th>Email</th>
    <th>Valid</th>
    <th>Options</th>
  </tr>
  <% if obj %>
    <% obj.each do |contact| %>
      <tr>
        <% begin %>
          <td><%= contact.name %></td>
          <td><%= (Date.parse contact.date).strftime("%Y %B %d") %></td>
          <td><%= contact.phone %></td>
          <td><%= contact.address %></td>
          <td><%= contact.franchise %></td>
          <td><%= contact.card_digit %></td>
          <td><%= contact.email %></td>
        <% rescue %>
          <td colspan="5">
            Some fields in this contact has a wrong format that produce erros
          </td>
        <% end %>
        <td>
          <% if contact.is_ok %> 
            <span class="badge badge-success"><%= contact.is_ok %></span>
          <% else %>
            <span class="badge badge-danger"><%= contact.is_ok %></span>
          <% end %>
        </td>
        <td><%= link_to 'view', contact_path(contact), class: 'btn btn-primary' %></td>
        
      </tr>
    <% end %>
  <% end %>
</table>

app/views/contacts/all_contact.html.erb
<h1>All contacts</h1><br><br>
<%= render 'contact_table', obj: @contacts %>

app/views/contacts/invalid_contact.html.erb
<h1>Invalid contact</h1><br><br>
<%= render 'contact_table', obj: @contacts %>

app/views/contacts/show.html.erb
<h2>
  <%= @contact.name %>
</h2>
<h5>
  Valid contact:
  <% if @contact.is_ok %> 
    <span class="badge badge-success"><%= @contact.is_ok %></span>
  <% else %>
    <span class="badge badge-danger"><%= @contact.is_ok %></span>
  <% end %>
</h5>
<br><br>

<% begin %>
<div class="row">
  <div class="col-md-auto">
    <h5>Date: </h5>
    <p><%= (Date.parse @contact.date).strftime("%Y %B %d") %></p>

    <h5>Phone: </h5>
    <p><%= @contact.phone %></p>
  </div>

  <div class="col-md-auto">
    <h5>Address: </h5>
    <p><%= @contact.address %></p>

    <h5>Email: </h5>
    <p><%= @contact.email %></p>
  </div>

  <div class="col-md-auto">
    <h5>Credit card: </h5>
    <p><%= @contact.card_digit %></p>

    <h5>Franchise: </h5>
    <p><%= @contact.franchise %></p>
  </div>

  <div class="col-md-auto">

    <h5>User: </h5>
    <p><%= @contact.user.username %></p>

    <h5>Book: </h5>
    <p><%= (@contact.book.file.filename).to_s.downcase %></p>
  </div>
  <% rescue %>
    <p class="lead">
      Some fields in this contact has a wrong format that produce erros
    </p>
  <% end %>
</div><br><br>

<% if @contact.messages %>
  <table class='table'>
    <tr>
      <th>#</th>
      <th>Errors</th>
    </tr>
    <% @contact.messages.each_with_index do |message, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= message.description %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/contacts/valid_contact.html.erb
<h1>Valid contact</h1><br><br>
<%= render 'contact_table', obj: @contacts %>

app/views/layouts/_navbar1.html.erb
<div class="wrapper">
  <!-- Sidebar -->
  <nav id="sidebar">
      <div class="sidebar-header">
          <h3>Sidebar</h3>
      </div>

      <ul class="list-unstyled components">
        <li><%= link_to 'My account', user_path(current_user) %></li>
          
          <li>
              <%= link_to 'Import book', new_book_path %>
          </li>
          <li>
              <%= link_to 'My books', books_path %>
          </li>

          <li>
              <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">My contacts</a>
              <ul class="collapse list-unstyled" id="pageSubmenu">
                  <li>
                      <%= link_to 'All contacts', all_contacts_path %>
                  </li>
                  <li>
                    <%= link_to 'Valid contacts', valid_contacts_path %>
                  </li>
                  <li>
                    <%= link_to 'Invalid contacts', invalid_contacts_path %>
                  </li>
              </ul>
          </li>
          <li>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          </li>
      </ul>
  </nav>

  <div id="content">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
                <span>Toggle Sidebar</span>
            </button>

            
          </div>
        </nav>
        
        <div class="container-fluid">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactImport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/navbar1' %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        
        <%= yield %>
            </div>
          </div>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
    
      

        

  </body>
</html>

app/views/pages/welcome.html.erb
<div class="container pt-5">
  <div class="jumbotron">
    <h1 class="display-4">Hello, welcome <%= current_user.username if user_signed_in? %></h1>
    <p class="lead">This is a simple contact import app, where you would import and store contact from a csv file.</p>
    <hr class="my-4">
    <% if !user_signed_in? %>
      <p>Register or log in to start using the app.</p>
      <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-success btn-lg' %>
      <%= link_to 'Log in', new_user_session_path, class: 'btn btn-primary btn-lg' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p><%= @user.email%></p>

<div class="row mb-5">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <table>
          <tr>
            <th><%= link_to 'Books', books_path %></th>
          </tr>
          <tr>
            <th class="pr-4">All</th>
            <th class="pr-4">Waiting</th>
            <th class="pr-4">Finished</th>
            <th class="pr-4">Failed</th>
          </tr>
          <tr>
            <td><%= @user.books.size %></td>
            <td><%= @books.espera.size %></td>
            <td><%= @books.terminado.size %></td>
            <td><%= @books.fallido.size %></td>
          </tr>
        </table>  
      </div>  
    </div>
  </div>

  <div class="col">
    <div class="card">
      <div class="card-body">
        <table>
          <tr>
            <th><%= link_to 'Contacts', all_contacts_path %></th>
          </tr>
          <tr>
            <th class="pr-4"><%= link_to 'All', all_contacts_path %></th>
            <th class="pr-4"><%= link_to 'Valid contact', valid_contacts_path %></th>
            <th class="pr-4"><%= link_to 'Invalid contact', invalid_contacts_path %></th>
          </tr>
          <tr>
            <td><%= @user.contacts.size %></td>
            <td><%= @valid_contacts.size %></td>
            <td><%= @invalid_contacts.size %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row mb-5">
  <div class="col">
    <h3 class="mb-3">Last 5 books</h3>
    <%= render 'books/book_table', obj: @user.books.last(5) %>
  </div>
</div>

<div class="row">
  <div class="col">
    <h3 class="mb-3">Last 5 contacts</h3>
    <%= render 'contacts/contact_table', obj: @last_contacts %>
  </div>
</div>